# Generated by Django 3.1.7 on 2021-03-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('ranks', '0001_initial'),
        ('users', '0003_auto_20210308_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='department id'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranks.rank', verbose_name='rank id'),
        ),
    ]
