# Generated by Django 3.1.7 on 2021-03-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_secret'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='task',
        ),
        migrations.AddField(
            model_name='report',
            name='task_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskprogress', verbose_name='task_progress_id'),
        ),
    ]
