# Generated by Django 3.1.7 on 2021-03-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_secret'),
        ('reports', '0003_remove_report_report_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_content',
            field=models.TextField(blank=True, null=True, verbose_name='report_content'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(default='', max_length=255, verbose_name='report_name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='task_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='tasks.taskprogress', verbose_name='task_progress_id'),
        ),
    ]
