# Generated by Django 3.1.7 on 2021-03-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_secret'),
        ('reports', '0004_auto_20210318_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='task_progress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='tasks.taskprogress', verbose_name='task_progress_id'),
        ),
    ]
