# Generated by Django 3.1.7 on 2021-03-09 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('priority', models.IntegerField(choices=[(1, 'none'), (2, 'low'), (3, 'normal'), (4, 'high'), (5, 'urgent')], default=1, verbose_name='priority')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start_date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end_date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner_id')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unread', 'unread'), ('working', 'working'), ('reported', 'reported'), ('pending', 'pending'), ('rejected', 'rejected'), ('completed', 'completed'), ('canceled', 'canceled')], default='unread', max_length=15, verbose_name='status')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_by_user_id', to=settings.AUTH_USER_MODEL, verbose_name='ordered_by')),
                ('ordered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_to_user_id', to=settings.AUTH_USER_MODEL, verbose_name='ordered_to')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='task_id')),
            ],
        ),
    ]
