# Generated by Django 3.1.7 on 2021-03-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210309_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='tasks.task', verbose_name='task_id'),
        ),
    ]
