# Generated by Django 3.1.7 on 2021-03-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210309_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='', max_length=255, verbose_name='task_name'),
        ),
    ]
