# Generated by Django 3.1.7 on 2021-03-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('department_image', models.ImageField(blank=True, null=True, upload_to='departments', verbose_name='department image')),
                ('founded_at', models.DateTimeField(blank=True, null=True, verbose_name='founded_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
    ]
