# Generated by Django 3.1.7 on 2021-03-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_name',
            field=models.TextField(verbose_name='attachment_name'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='attachment_type'),
        ),
    ]
